@startuml e6
partition Equipe {
(*) --> "Construir documento de requisitos"
}

partition DiagramaDeComponentes {
--> "Identificar componentes da arquitetura"
--> ===B1===
--> "Identificar relações entre os componentes da arquitetura"
--> "Construir diagrama de componentes"
--> ===B2===
}

partition ModeloConceitual {
===B1=== --> "Identificar classes de elementos de componentes"
--> "Refinar classes"
--> "Identificar atributos das classes"
--> "Identificar relações entre as classes"
--> "Refinar relações entre as classes"
--> "Construir modelo conceitual"
--> ===B2===
}

partition DiagramaDeInteração {
--> "Identificar interações entre elementos"
If "Sequência temporal é o foco principal?" then
--> [Sim] "Decidir construir diagramas de sequência"
--> "Construir diagramas de interação"
else
--> [Não] "Decidir construir diagramas de comunicação"
Endif
--> "Construir diagramas de interação"
}

partition DiagramaDeClasses {
--> "Construir diagrama de classes de projeto"
}

partition Código-fonte {
--> "Gerar código-fonte"
}

partition Equipe {
--> (*)
}
@enduml