@startuml fazer_matricula
actor Estudante
Estudante->"user: Estudante": 1: fazerMatricula(idDisciplina)
activate "user: Estudante"
"user: Estudante"->Disciplina: 1.1: disciplinaExiste(idDisciplina)
activate "Disciplina"
Disciplina-->"user: Estudante": existe 
deactivate "Disciplina"
alt existe
"user: Estudante"->"user: Estudante": 1.2: sucesso = inserirDisciplinaMatriculadaNaBD(idDisciplina)
alt sucesso
"user: Estudante"-->Estudante: mensagemDeSucesso
else else
"user: Estudante"-->Estudante: mensagemDeErro
end
else else
"user: Estudante"-->Estudante: mensagemDeErro
end
deactivate "user: Estudante"
@enduml