@startuml realizar_cadastro
actor Visitante

Visitante->"user: Visitante": 1: realizarCadastro(nome, email, senha)
Activate "user: Visitante"
"user: Visitante"->"user: Visitante": 1.1: validou = validarDados(nome, email, senha)

alt validou
"user: Visitante"->"user: Visitante": 1.2: sucesso = inserirUsuarioNaBD(nome, email, senha)
alt sucesso
"user: Visitante"-->Visitante: mensagemDeSucesso
else else
"user: Visitante"-->Visitante: mensagemDeErro
end
else else
"user: Visitante"-->Visitante: mensagemDeErro
end
deactivate "user: Visitante"

@enduml