@startuml realizar_cadastro
actor Visitante

Visitante->"user: Visitante": 1: realizarCadastro(nome, email, senha)
Activate "user: Visitante"
"user: Visitante"->"user: Visitante": 1.1: validarDados(nome, email, senha)

alt validarDados
"user: Visitante"->"user: Visitante": 1.2: inserirUsuarioNaBD(nome, email, senha)
alt inserirUsuarioNaBD
"user: Visitante"-->Visitante: mensagemDeSucesso
else else
"user: Visitante"-->Visitante: mensagemDeErro
end
else else
"user: Visitante"-->Visitante: mensagemDeErro
end
deactivate "user: Visitante"

@enduml