@startuml realizar_Sistema
actor Visitante

Visitante->Secretaria: 1: realizarCadastro(nome, email, senha)
Activate Secretaria
Secretaria->Secretaria: 1.1: validarDados(nome, email, senha)

alt validarDados
Secretaria->Secretaria: 1.2: inserirUsuarioNaBD(nome, email, senha)
alt inserirUsuarioNaBD
Secretaria-->Visitante: mensagemDeSucesso
else else
Secretaria-->Visitante: mensagemDeErro
end
else else
Secretaria-->Visitante: mensagemDeErro
end
deactivate Secretaria

@enduml